src/Zeta.AgentosCRM.Web.Mvc/Areas/AppAreaName/Controllers/WebhookSubscriptionController.cs
using System;
using System.Threading.Tasks;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Webhooks;
using Microsoft.AspNetCore.Mvc;
using Zeta.AgentosCRM.Authorization;
using Zeta.AgentosCRM.Web.Areas.AppAreaName.Models.Webhooks;
using Zeta.AgentosCRM.Web.Controllers;
using Zeta.AgentosCRM.WebHooks;

namespace Zeta.AgentosCRM.Web.Areas.AppAreaName.Controllers
{
    [Area("AppAreaName")]
    [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription)]
    public class WebhookSubscriptionController : AgentosCRMControllerBase
    {
        private readonly IWebhookSubscriptionAppService _webhookSubscriptionAppService;
        private readonly IWebhookEventAppService _webhookEventAppService;

        public WebhookSubscriptionController(
            IWebhookSubscriptionAppService webhookSubscriptionAppService,
            IWebhookEventAppService webhookEventAppService
            )
        {
            _webhookSubscriptionAppService = webhookSubscriptionAppService;
            _webhookEventAppService = webhookEventAppService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Edit)]
        public async Task<IActionResult> EditModal(string subscriptionId)
        {
            if (string.IsNullOrWhiteSpace(subscriptionId))
            {
                throw new ArgumentException(nameof(subscriptionId));
            }

            var availableWebhooks = await _webhookSubscriptionAppService.GetAllAvailableWebhooks();
            var model = new CreateOrEditWebhookSubscriptionViewModel()
            {
                WebhookSubscription = await _webhookSubscriptionAppService.GetSubscription(subscriptionId),
                AvailableWebhookEvents = availableWebhooks
            };

            return PartialView("_CreateOrEditModal", model);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Create)]
        public async Task<IActionResult> CreateModal()
        {
            var availableWebhooks = await _webhookSubscriptionAppService.GetAllAvailableWebhooks();
            var model = new CreateOrEditWebhookSubscriptionViewModel()
            {
                WebhookSubscription = new WebhookSubscription(),
                AvailableWebhookEvents = availableWebhooks
            };

            return PartialView("_CreateOrEditModal", model);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Detail)]
        public async Task<IActionResult> Detail(string id)
        {
            var subscription = await _webhookSubscriptionAppService.GetSubscription(id);

            return View(subscription);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Create)]
        public async Task<IActionResult> WebHookEventDetail(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                throw new ArgumentException(nameof(id));
            }

            var webhookEvent = await _webhookEventAppService.Get(id);
            return View(webhookEvent);
        }
    }
}

src/Zeta.AgentosCRM.Web.Mvc/Areas/AppAreaName/Views/WebhookSubscription/Detail.cshtml
@using Zeta.AgentosCRM.Authorization
@using Zeta.AgentosCRM.Web.TagHelpers
@model Abp.Webhooks.WebhookSubscription

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/WebhookSubscriptions/Detail.css" asp-append-version="true"/>
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/Common/_KeyValueListManager.css" asp-append-version="true"/>

}

@section Scripts
{
    <script>
        var subscriptionData = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model, Newtonsoft.Json.Formatting.Indented));
    </script>
    <script abp-src="/view-resources/Areas/AppAreaName/Views/_Bundles/webhook-subscription-detail.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Areas/AppAreaName/Views/Common/_KeyValueListManager.js" asp-append-version="true"></script>

}

@{
    var breadcrumbs = new List<BreadcrumbItem>()
    {
        new BreadcrumbItem(Url.Action("Index", "WebhookSubscription", new {Area = "AppAreaName"}), @L("WebhookSubscriptions")),
        new BreadcrumbItem(L("WebhookSubscriptionDetail")),
    };
}

<abp-page-subheader title="@L("WebhookSubscriptionDetail")" breadcrumbs="breadcrumbs">
    @if (Model.IsActive)
    {
        <span class="badge badge-success">@L("Active")</span>
    }
    else
    {
        <span class="badge badge-dark">@L("Disabled")</span>
    }

    @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Edit) ||
         IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_ChangeActivity))
    {
        <div class="dropdown dropdown-inline ml-2">
            <a href="#" class="btn btn-icon" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class="flaticon-more-1"></i>
            </a>
            <!--begin::Naviigation-->
            <ul class="dropdown-menu p-0 m-0 dropdown-menu-md dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-211px, 39px, 0px); top: 0px; left: 0px; will-change: transform;">
                @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Edit))
                {
                    <li>
                        <a href="javascript:;" id="subscription-edit-btn" class="dropdown-item">
                            @L("EditWebhookSubscription")
                        </a>
                    </li>
                }

                @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_ChangeActivity))
                {
                    <li>
                        <a href="javascript:;" id="activity-toggle-btn" class="dropdown-item">

                            @if (Model.IsActive)
                            {
                                @L("Disable")
                            }
                            else
                            {
                                @L("Enable")
                            }
                        </a>
                    </li>
                }
            </ul>
        </div>
    }
</abp-page-subheader>

<div class="@(await GetContainerClass())">
    <div class="card mb-5" id="portlet-detail">
        <div class="card-body">
            <div class="mb-5 row">
                <label class="col-2 form-label">@L("WebhookEndpoint")</label>
                <div class="col-10 text-break">
                    @Model.WebhookUri
                </div>
            </div>
            <div class="mb-5 row">
                <label class="col-2 form-label">@L("WebhookEvents")</label>
                <div class="col-10 text-break">
                    @if (Model.Webhooks != null)
                    {
                        @foreach (var webhookEvent in Model.Webhooks)
                        {
                            @webhookEvent
                            <br/>
                        }
                    }
                </div>
            </div>

            <div class="mb-5 row">
                <label class="col-2 form-label">@L("AdditionalWebhookHeaders")</label>
                <div class="col-10 text-break">
                    @if (Model.Headers != null)
                    {
                        @foreach (var webhookHeader in Model.Headers)
                        {
                            @webhookHeader
                            <br/>
                        }
                    }
                </div>
            </div>

            <div class="mb-5 row mb-0">
                <label class="col-2 form-label">@L("WebhookSecret")</label>
                <div class="col-10 position-relative">
                    <span class="blur" id="secretSpan">@Model.Secret</span>
                    <div class="btn btn-sm btn-dark btn-elevate btn-elevate-air" id="secret-view-btn">@L("ViewWebhookSecret")</div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header align-items-center border-0 mt-4">
            <h3>
                @L("WebhookSendAttempts")
            </h3>
            <div class="card-toolbar">
                <button id="refresh-send-attempts-btn" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm">
                    <i class="flaticon2-refresh"></i>
                </button>
            </div>
        </div>

        <div class="card-body">
            <div class="align-items-center">
                <table id="WebHookSendAttemptTable" class="table align-middle table-row-dashed fs-6 gy-5 dataTable dtr-inline no-footer">
                    <thead>
                    <tr>
                        <th></th>
                        <th style="text-align: center;width: 60px">@L("Actions")</th>
                        <th>@L("WebhookEvent")</th>
                        <th>@L("WebhookEventId")</th>
                        <th>@L("CreationTime")</th>
                        <th>@L("HttpStatusCode")</th>
                        <th>@L("Response")</th>
                        <th>@L("Data")</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="SendAttemptDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

src/Zeta.AgentosCRM.Web.Mvc/Areas/AppAreaName/Views/WebhookSubscription/Index.cshtml
@using Zeta.AgentosCRM.Authorization
@using Zeta.AgentosCRM.Web.Areas.AppAreaName.Startup
@{
    ViewBag.CurrentPageName = AppAreaNamePageNames.Common.WebhookSubscriptions;
}

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/WebhookSubscriptions/Index.css" asp-append-version="true"/>
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/Common/_KeyValueListManager.css" asp-append-version="true"/>
}

@section Scripts
{
    <script abp-src="/view-resources/Areas/AppAreaName/Views/_Bundles/webhook-subscription-list.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Areas/AppAreaName/Views/Common/_KeyValueListManager.js" asp-append-version="true"></script>
}

<abp-page-subheader title="@L("WebhookSubscriptions")" description="@L("WebhookSubscriptionsInfo")">
    @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Create))
    {
        <button id="CreateNewWebhookSubscription" class="btn btn-primary">
            <i class="fa fa-plus btn-md-icon"></i>
            <span class="d-none d-md-inline-block">
                @L("AddNewWebhookSubscription")
            </span>
        </button>
    }
</abp-page-subheader>

<div class="@(await GetContainerClass())">
    <div class="card">
        <div class="card-body">
            <div class="align-items-center">
                <div class="col-md-12">
                    <div class="alert bg-light-primary d-flex align-items-center p-5 mb-10">
                        <span class="svg-icon svg-icon-2hx svg-icon-primary me-4">
                            <svg class="flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                                <use xlink:href="#warning-icon"/>
                            </svg>
                        </span>
                        <div class="d-flex flex-column">
                            <span>@L("WebhookPageInfo")</span>
                        </div>
                        <button type="button" class="btn-close position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                        </button>
                    </div>
                </div>
                <table id="SubscriptionTable" class="table align-middle table-row-dashed fs-6 gy-5 dataTable dtr-inline no-footer">
                    <thead>
                    <tr>
                        <th></th>
                        <th style="width:100px;"></th>
                        <th>@L("WebhookEndpoint")</th>
                        <th>@L("WebhookEvents")</th>
                        <th>@L("IsActive")</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

src/Zeta.AgentosCRM.Web.Mvc/Areas/AppAreaName/Views/WebhookSubscription/WebHookEventDetail.cshtml
@using Zeta.AgentosCRM.Authorization
@model Abp.Webhooks.WebhookEvent

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/WebhookSubscriptions/Detail.css" asp-append-version="true"/>
}

@section Scripts
{
    <script>
        var webhookEventId = "@Html.Raw(Model.Id)";
    </script>
    <script abp-src="/view-resources/Areas/AppAreaName/Views/_Bundles/webhook-event-detail.js" asp-append-version="true"></script>
}

@{
    int maxDataLength = 300;
}
<abp-page-subheader title="@L("WebhookEventDetail")"></abp-page-subheader>
<div class="@(await GetContainerClass()) d-flex flex-column-fluid">
    <div class="container">
        <div class="card" id="portlet-detail">
            <div class="card-body">
                <div class="mb-5 row">
                    <label class="col-2 form-label">@L("WebhookEvent")</label>
                    <div class="col-10">
                        @Model.WebhookName
                    </div>
                </div>
                <div class="mb-5 row">
                    <label class="col-2 form-label">@L("CreationTime")</label>
                    <div class="col-10">
                        @Model.CreationTime
                    </div>
                </div>

                <div class="mb-5 row">
                    <label class="col-2 form-label">@L("Data")</label>
                    <div class="col-10 text-break">
                        @if (Model.Data.Length <= maxDataLength)
                        {
                            @Model.Data
                        }
                        else
                        {
                            <p>
                                <span id="dataDots">@Model.Data.Substring(0, maxDataLength). . .</span>
                                <span id="dataMore" class="d-none">@Model.Data</span>
                            </p>
                            <button class="btn btn-outline-primary btn-sm" id="dataShowMoreBtn">@L("ShowData")</button>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header align-items-center border-0 mt-4">
                <h3 class="card-title align-items-start flex-column">
                    <span class="fw-bolder text-dark">@L("WebhookSendAttempts")</span>
                </h3>
                <div class="card-toolbar">
                    <button id="refresh-send-attempts-btn" class="btn btn-outline-brand btn-sm btn-icon btn-icon-md">
                        <i class="flaticon2-refresh"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="align-items-center">
                    <table id="WebhookEventDetailSendAttemptsTable" class="table align-middle table-row-dashed fs-6 gy-5 dataTable dtr-inline no-footer">
                        <thead>
                        <tr>
                            <th style="width: 10px"></th>
                            <th style="width: 60px;text-align: center">@L("Actions")</th>
                            <th style="width: 60px;text-align: center">@L("WebhookSubscriptionId")</th>
                            <th style="text-align: center">@L("WebhookEndpoint")</th>
                            <th style="width: 60px;">@L("CreationTime")</th>
                            <th style="width: 120px;">@L("HttpStatusCode")</th>
                            <th>@L("Response")</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="SendAttemptDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

src/Zeta.AgentosCRM.Web.Mvc/Areas/AppAreaName/Views/WebhookSubscription/_CreateOrEditModal.cshtml
@using Zeta.AgentosCRM.Web.Areas.AppAreaName.Models.Common.Modals
@model Zeta.AgentosCRM.Web.Areas.AppAreaName.Models.Webhooks.CreateOrEditWebhookSubscriptionViewModel

<script>
    var createOrEditIsEdit = @Html.Raw(Model.WebhookSubscription.Id == default ? "false" : "true");
    var createOrEditHeaders = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.WebhookSubscription.Headers, Newtonsoft.Json.Formatting.Indented));
</script>
<link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/WebhookSubscriptions/_CreateOrEditModal.css" asp-append-version="true"/>

@await Html.PartialAsync("~/Areas/AppAreaName/Views/Common/Modals/_ModalHeader.cshtml",
    new ModalHeaderViewModel(Model.WebhookSubscription.Id == default ? L("AddNewWebhookSubscription") : L("EditWebhookSubscription")))

<div class="modal-body">
    <form name="WebhookSubscriptionForm" role="form" novalidate class="form-validation">
        @if (Model.WebhookSubscription.Id != default)
        {
            <input type="hidden" name="Id" value="@Model.WebhookSubscription.Id"/>
        }

        <div class="mb-5">
            <label for="webhookUri" class="form-label">@L("WebhookEndpoint")</label>
            <input id="webhookEndpointURL" type="text" name="webhookUri" class="form-control" value="@Model.WebhookSubscription.WebhookUri" placeholder="https://example.com/postreceive" required>
        </div>

        <div class="mb-5">
            <label for="webhookUri" class="form-label">@L("WebhookEvents")</label>
            @Html.DropDownList(
                "Webhooks",
                Model.AvailableWebhookEvents.Items.Select(e => new SelectListItem(e.DisplayName ?? e.Name, e.Name, Model.WebhookSubscription.Webhooks.Contains(e.Name)))
                , new {@class = "form-control select2 col-12", multiple = "multiple", style = "width: 100%;", @required = "required"}
                )
        </div>

        <hr/>
        <div class="mb-5">
            <label for="webhookUri" class="form-label">@L("AdditionalWebhookHeaders")</label>
            <div id="additional-header-list">

            </div>
        </div>
    </form>
</div>

@await Html.PartialAsync("~/Areas/AppAreaName/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")